### ISSUE TITLE
[FEATURE] Create web application version

### ISSUE THREAD

**Issue by iwatake2222** [iwatake2222/rotation_master#38]
## The reason **WHY** this new feature is needed
- It must be useful if the app runs on a browser

## Describe **WHAT** this new feature is
- Create a web application version

## **HOW** to achieve this new feature
- Implement under the following directory:
    - https://github.com/iwatake2222/rotation_master/tree/master/web
- Port all logic to JavaScript or TypeScript
- The following libraries may be useful
    - https://github.com/KhronosGroup/WebGL
    - https://github.com/jnmaloney/WebGui

## Related issues
- Parent issue
    - None
- Related issue
    - None

## Additional context
None

**Comment by naftalimurgor** [comment]
Hi, 

I've looked at the application and I found it so interesting. I'm a C++ programmer and would like to port the application to we version using TypeScript and Threejs library. Feel free to let me know what I need to get started with this.

Thanks

**Comment by iwatake2222** [comment]
@naftalimurgor 
Thank you!! It will be really great if we can run it on a browser. However, I just started another project, so I'm not working on this issue for the time being. Also, I'm new to web application development and don't have any plan how to make it at all... 
It's just an idea but maybe we can base on https://www.andre-gaschler.com/rotationconverter/ All conversions are already implemented, so basically all we need will be drawing axes and object using the calculated rotate matrix.

**Comment by naftalimurgor** [comment]
Hey,
I got busy and won't be abe to find time working on this issue.

**Comment by iwatake2222** [comment]
https://github.com/astomih/rotation_master
https://astomih.github.io/rotation_master/
